"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateHtmlPage = generateHtmlPage;
exports.generateDirectoryPageHtml = generateDirectoryPageHtml;
const path = __importStar(require("path"));
function generateBreadcrumbs(currentPath, isFile = false) {
    const segments = currentPath.split(path.sep).filter(Boolean);
    let breadcrumbsHtml = '<a href="/">Home</a>';
    let currentLink = '';
    segments.forEach((segment, index) => {
        currentLink += '/' + segment;
        if (isFile && index === segments.length - 1) {
            // For the file itself, don't link to index.html
            breadcrumbsHtml += ` / ${segment}`;
        }
        else {
            breadcrumbsHtml += ` / <a href="${currentLink}/index.html">${segment}</a>`;
        }
    });
    return breadcrumbsHtml;
}
function generateHtmlPage(title, content, currentPath) {
    const breadcrumbs = generateBreadcrumbs(currentPath, true);
    // For markdown files, the breadcrumbs themselves are toggleable
    const toggleableBreadcrumbs = `
        <span class="toggle-icon">▶</span>
        <div class="toggle-content" style="display:none;">
            <nav>${breadcrumbs}</nav>
        </div>
    `;
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        .toggle-icon {
            cursor: pointer;
            display: inline-block;
            width: 1em; /* Adjust as needed */
        }
    </style>
</head>
<body>
    <header>
        ${toggleableBreadcrumbs}
        <h1>${currentPath}</h1>
    </header>
    <main>
        ${content}
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
}
// Generates only the <ul><li>...</li></ul> content for a directory listing
function generateDirectoryListContent(currentPath, items, allDirectoryStructure) {
    let listItemsHtml = '';
    // Sort items: directories first, then files, both alphabetically
    const sortedItems = items.sort((a, b) => {
        if (a.type === 'directory' && b.type === 'file')
            return -1;
        if (a.type === 'file' && b.type === 'directory')
            return 1;
        return a.name.localeCompare(b.name);
    });
    sortedItems.forEach(item => {
        if (item.type === 'directory') {
            const subDirKey = path.join(currentPath, item.name).substring(1); // e.g., 'posts/2025/07'
            const subDirItems = allDirectoryStructure.get(subDirKey) || [];
            const nestedList = generateDirectoryListContent(path.join(currentPath, item.name), subDirItems, allDirectoryStructure); // Recursive call
            listItemsHtml += `
                <li>
                    <span class="toggle-icon">▶</span> <a href="${item.link}">${item.name}/</a>
                    <div class="toggle-content" style="display:none;">
                        <ul>${nestedList}</ul>
                    </div>
                </li>`;
        }
        else {
            listItemsHtml += `<li><a href="${item.link}">${item.name}</a></li>`;
        }
    });
    return listItemsHtml;
}
// Generates the full HTML page for a directory listing
function generateDirectoryPageHtml(currentPath, items, allDirectoryStructure) {
    const breadcrumbs = generateBreadcrumbs(currentPath, false);
    const directoryListContent = generateDirectoryListContent(currentPath, items, allDirectoryStructure);
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index of ${currentPath}</title>
    <style>
        .toggle-icon {
            cursor: pointer;
            display: inline-block;
            width: 1em; /* Adjust as needed */
        }
    </style>
</head>
<body>
    <header>
        <nav>${breadcrumbs}</nav>
        <h1>Index of ${currentPath}</h1>
    </header>
    <main>
        <ul>
            ${directoryListContent}
        </ul>
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
}
