

function generateBreadcrumbs(currentPath: string, isFile: boolean = false): string {
    const segments = currentPath.split('/').filter(Boolean);
    let breadcrumbsHtml = '<a href="/">Home</a>';
    let currentLink = '';

    segments.forEach((segment, index) => {
        currentLink += '/' + segment;
        if (isFile && index === segments.length - 1) {
            // For the file itself, don't link to index.html
            breadcrumbsHtml += ` / ${segment}`;
        } else {
            breadcrumbsHtml += ` / <a href="${currentLink}/index.html">${segment}</a>`;
        }
    });
    return breadcrumbsHtml;
}

export function generateHtmlPage(title: string, content: string, currentPath: string): string {
    const breadcrumbs = generateBreadcrumbs(currentPath, true);
    // For markdown files, the breadcrumbs themselves are toggleable
    const toggleableBreadcrumbs = `
        <span class="toggle-icon">▶</span>
        <div class="toggle-content" style="display:none;">
            <nav>${breadcrumbs}</nav>
        </div>
    `;

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        .toggle-icon {
            cursor: pointer;
            display: inline-block;
            width: 1em; /* Adjust as needed */
        }
    </style>
</head>
<body>
    <header>
        <nav>${breadcrumbs}</nav>
        <h1>${currentPath}</h1>
    </header>
    <main>
        ${content}
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
    return addToggleFunctionality(html);
}

interface DirectoryItem {
    name: string;
    type: 'file' | 'directory';
    link: string; // Link relative to the current index.html
}

// Generates only the <ul><li>...</li></ul> content for a directory listing
function generateDirectoryListContent(currentPath: string, items: DirectoryItem[], allDirectoryStructure: Map<string, DirectoryItem[]>): string {
    let listItemsHtml = '';

    // Sort items: directories first, then files, both alphabetically
    const sortedItems = items.sort((a, b) => {
        if (a.type === 'directory' && b.type === 'file') return -1;
        if (a.type === 'file' && b.type === 'directory') return 1;
        return a.name.localeCompare(b.name);
    });

    sortedItems.forEach(item => {
        if (item.type === 'directory') {
            listItemsHtml += `
                <li>
                    <span class="toggle-icon">▶</span> <a href="${item.link}">${item.name}/</a>
                    <div class="toggle-content" style="display:none;" data-src="/${item.link.endsWith('/index.html') ? item.link : item.link + '/index.html'}">
                        <!-- Content will be loaded dynamically here -->
                    </div>
                </li>`;
        } else {
            listItemsHtml += `
                <li>
                    <span class="toggle-icon">▶</span> <a href="${item.link}">${item.name}</a>
                    <div class="toggle-content" style="display:none;" data-src="/${item.link}">
                        <!-- Content will be loaded dynamically here -->
                    </div>
                </li>`;
        }
    });

    return listItemsHtml;
}

import {addToggleFunctionality} from "./toggleGenerator";

// Generates the full HTML page for a directory listing
export function generateDirectoryPageHtml(currentPath: string, items: DirectoryItem[], allDirectoryStructure: Map<string, DirectoryItem[]>): string {
    const breadcrumbs = generateBreadcrumbs(currentPath, false);
    const directoryListContent = generateDirectoryListContent(currentPath, items, allDirectoryStructure);

    let html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index of ${currentPath}</title>
    <style>
        .toggle-icon {
            cursor: pointer;
            display: inline-block;
            width: 1em; /* Adjust as needed */
        }
    </style>
</head>
<body>
    <header>
        <nav>${breadcrumbs}</nav>
        <h1>Index of ${currentPath}</h1>
    </header>
    <main>
        <ul>
            ${directoryListContent}
        </ul>
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
    return addToggleFunctionality(html);
}