function generateBreadcrumbs(currentPath: string, isFile: boolean = false): string {
    const segments = currentPath.split('/').filter(Boolean);
    let breadcrumbsHtml = '<a href="/">Home</a>';
    let currentLink = '';

    segments.forEach((segment, index) => {
        currentLink += '/' + segment;
        if (isFile && index === segments.length - 1) {
            // For the file itself, link to the HTML file
            breadcrumbsHtml += ` / <a href="${currentLink}.html">${segment}</a>`;
        } else {
            breadcrumbsHtml += ` / <a href="${currentLink}/index.html">${segment}</a>`;
        }
    });
    return breadcrumbsHtml;
}

export function generateHtmlPage(title: string, content: string, currentPath: string): string {
    const breadcrumbs = generateBreadcrumbs(currentPath, true);
    // For markdown files, the breadcrumbs themselves are toggleable
    const toggleableBreadcrumbs = `
        <span class="toggle-icon">▶</span>
        <div class="toggle-content" style="display:none;">
            <nav>${breadcrumbs}</nav>
        </div>
    `;

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="/assets/normalize.css">
    <style>
    .toggle-icon {
        cursor: pointer;
        display: inline-block;
    }
    .triangle-toggle {
        width: 0;
        height: 0;
        border-left: 4px solid transparent;
        border-right: 4px solid transparent;
        border-top: 8px solid #333;
        cursor: pointer;
        transition: transform 0.3s ease;
        display: inline-block;
        vertical-align: middle;
        margin-right: 6px;
        margin-left: -14px; /* Move the icon outside the text area like default markers */
        transform: rotate(-90deg); /* Points right by default */
    }
    .triangle-toggle.toggled {
        transform: rotate(0deg); /* Points down when toggled */
    }
    li.has-toggle {
        list-style-type: none;
    }
</style>
</head>
<body>
    <header>
        <nav>${breadcrumbs}</nav>
        <h1>${currentPath}</h1>
    </header>
    <main>
        ${content}
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
    return addToggleFunctionality(html);
}

interface DirectoryItem {
    name: string;
    type: 'file' | 'directory';
    link: string; // Link relative to the current index.html
}

// Generates only the <ul><li>...</li></ul> content for a directory listing
function generateDirectoryListContent(currentPath: string, items: DirectoryItem[], allDirectoryStructure: Map<string, DirectoryItem[]>): string {
    let listItemsHtml = '';

    // Add parent directory link (../)
    const parentPath = currentPath.substring(0, currentPath.lastIndexOf('/'));
    if (currentPath !== '/') {
        listItemsHtml += `
            <li><a href="${parentPath === '' ? '/' : parentPath}/index.html">../</a></li>`;
    }

    // Sort items: directories first, then files, both alphabetically
    const sortedItems = items.sort((a, b) => {
        if (a.type === 'directory' && b.type === 'file') return -1;
        if (a.type === 'file' && b.type === 'directory') return 1;
        return a.name.localeCompare(b.name);
    });

    sortedItems.forEach(item => {
        if (item.type === 'directory') {
            listItemsHtml += `
                <li class="has-toggle">
                    <span class="toggle-icon triangle-toggle"></span><a href="/${item.link}">${item.name}/</a>
                    <div class="toggle-content" style="display:none;" data-src="/${item.link.endsWith('/index.html') ? item.link : item.link + '/index.html'}">
                        <!-- Content will be loaded dynamically here -->
                    </div>
                </li>`;
        } else {
            listItemsHtml += `
                <li class="has-toggle">
                    <span class="toggle-icon triangle-toggle"></span><a href="/${item.link}">${item.name}</a>
                    <div class="toggle-content" style="display:none;" data-src="/${item.link}">
                        <!-- Content will be loaded dynamically here -->
                    </div>
                </li>`;
        }
    });

    return listItemsHtml;
}

import {addToggleFunctionality} from "./toggleGenerator";

// Generates the full HTML page for a directory listing
export function generateDirectoryPageHtml(currentPath: string, items: DirectoryItem[], allDirectoryStructure: Map<string, DirectoryItem[]>): string {
    const breadcrumbs = generateBreadcrumbs(currentPath, false);
    const directoryListContent = generateDirectoryListContent(currentPath, items, allDirectoryStructure);

    let html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index of ${currentPath}</title>
    <link rel="stylesheet" href="/assets/normalize.css">
    <style>
        .toggle-icon {
            cursor: pointer;
            display: inline-block;
        }
        .triangle-toggle {
            width: 0;
            height: 0;
            border-left: 4px solid transparent;
            border-right: 4px solid transparent;
            border-top: 8px solid #333;
            cursor: pointer;
            transition: transform 0.3s ease;
            display: inline-block;
            vertical-align: middle;
            margin-right: 6px;
            margin-left: -14px; /* Move the icon outside the text area like default markers */
            transform: rotate(-90deg); /* Points right by default */
        }
        .triangle-toggle.toggled {
            transform: rotate(0deg); /* Points down when toggled */
        }
        li.has-toggle {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <nav>${breadcrumbs}</nav>
        <h1>Index of ${currentPath}</h1>
    </header>
    <main>
        <ul>
            ${directoryListContent}
        </ul>
    </main>
    <footer>
        <p>Generated by Static Blog Generator</p>
    </footer>
</body>
</html>
`;
    return addToggleFunctionality(html);
}
